version: "2"
run:
  build-tags:
    - integration
linters:
  enable:
    - asciicheck
    - bidichk
    - contextcheck
    - dupl
    - durationcheck
    - errname
    - errorlint
    - importas
    - makezero
    - misspell
    - nilerr
    - nilnil
    - nolintlint
    - prealloc
    - staticcheck
    - thelper
    - wastedassign
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    staticcheck:
      checks:
        - all
        - "-QF1001" # disable "Apply De Morgan's law".
        # The use of Go ideomatic identifiers is a recommendation, not a law.
        - "-ST1003" # disable "Poorly chosen identifier".
        - "-QF1008" # disable "Omit embedded fields from selector expression".

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - staticcheck
        path: webapp/
    paths:
      - bat/*/
      - bwtester/*/
      # - webapp/*/
      # - ssh/*/
      # - skip/*/
      # - netcat/*/
      # - web-gateway/*/
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/netsec-ethz/scion-apps)
  exclusions:
    generated: lax
    paths:
      - bat/color.go
      - bat/bench.go
      - bat/pb.go
      - bat/http.go
      - bat/*/
      - third_party$
      - builtin$
      - examples$
