# Configuration for golangci-lint for scion-apps.
# See https://github.com/golangci/golangci-lint#config-file

linters:
  enable:
    # enabled by default:
    #- deadcode
    #- errcheck
    #- gosimple
    #- govet
    #- ineffassign
    #- staticcheck
    #- structcheck
    #- typecheck
    #- unused
    #- varcheck
    - asciicheck
    - bidichk
    - contextcheck
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exportloopref
    - gci
    - gofmt
    #- ifshort
    - importas
    - makezero
    - misspell
    - nilerr
    - nilnil
    - nolintlint
    - prealloc
    - stylecheck
    - thelper
    - wastedassign
    - tenv

issues:
  # XXX exclude some linters where there are too many issues to fix now
  exclude-rules:
    - path: webapp/
      linters:
        - stylecheck
        - staticcheck
        - errcheck
  # Bat is mostly copied third-party code that we don't care to fix
  # Modifications are only (?) in bat/bat.go
  exclude-dirs:
    - bat/*/
  exclude-files:
    - bat/color.go
    - bat/bench.go
    - bat/pb.go
    - bat/http.go
  max-same-issues: 0

linters-settings:
  gci:
    local-prefixes: github.com/netsec-ethz/scion-apps
  exhaustive:
    default-signifies-exhaustive: true

run:
  build-tags: integration
