# Configuration for golangci-lint for scion-apps.
# See https://github.com/golangci/golangci-lint#config-file

linters:
  enable:
    # enabled by default:
    #- deadcode
    #- errcheck
    #- gosimple
    #- govet
    #- ineffassign
    #- staticcheck
    #- structcheck
    #- typecheck
    #- unused
    #- varcheck
    - gofmt
    - stylecheck # replacement for golint
    - dupl
    - misspell


issues:
  # XXX exclude some linters where there are too many issues to fix now
  exclude-rules:
    - path: bwtester/
      linters:
        - stylecheck
    - path: webapp/
      linters:
        - stylecheck
        - staticcheck
        - errcheck
    - path: ssh/
      linters:
        - errcheck
        

  max-same-issues: 0

run:
  # Bat is mostly copied third-party code that we don't care to fix
  # Modifications are only (?) in bat/bat.go
  skip-dirs:
    - bat/*/
  skip-files:
    - bat/color.go
    - bat/bench.go
    - bat/pb.go
    - bat/http.go
