version: "2"
run:
  build-tags:
    - integration
linters:
  enable:
    - asciicheck
    - bidichk
    - contextcheck
    - dupl
    - durationcheck
    - errname
    - errorlint
    - importas
    - makezero
    - misspell
    - nilerr
    - nilnil
    - nolintlint
    - prealloc
    - staticcheck
    - thelper
    - wastedassign
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    staticcheck:
      checks:
        - all
        - "-QF1001" # disable "Apply De Morgan's law".
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
issues:
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(examples)
  exclusions:
    generated: lax
