#!/bin/bash

mkdir -p ${cfgdir}

# Create script to set interfaces and run the SIG
file=${cfgdir}/run_sig${IA}.sh
cat >$file <<EOL
#!/bin/bash

# Webapp SIG Server Test

# Do not edit, this file is autogenerated by webapp.

# WARNING: the SIG binary must be built beforehand to this location:
# ${APPS_ROOT}/sig

# Set the linux capabilities on the binary:
sudo setcap cap_net_admin+eip ${APPS_ROOT}/sig

# Enable routing:
sudo sysctl net.ipv4.conf.default.rp_filter=0
sudo sysctl net.ipv4.conf.all.rp_filter=0
sudo sysctl net.ipv4.ip_forward=1

# Create a dummy interface:
sudo modprobe dummy

sudo ip link add dummy${IdRemote} type dummy
sudo ip addr add 172.16.0.${IdRemote}/32 brd + dev dummy${IdRemote} label dummy${IdRemote}:0

# Add the routing rules for the SIG:
sudo ip rule add to 172.16.${IdLocal}.0/24 lookup ${IdRemote} prio ${IdRemote}

# Start the SIG with the following command:
${APPS_ROOT}/sig -config=${cfgdir}/sig${IA}.config > ${cfgdir}/sig${IA}-1.log 2>&1 &

# Show the ip rules and routes
sudo ip rule show
sudo ip route show table ${IdLocal}
sudo ip route show table ${IdRemote}

# Add a server on host Local:
sudo ip link add server type dummy
sudo ip addr add 172.16.${IdLocal}.1/24 brd + dev server label server:0

# Create a simple html page to serve:
mkdir -p ${STATIC_ROOT}/data/www/sig${IA}
cd ${STATIC_ROOT}/data/www/sig${IA}
echo "Hello World from ${IAd}!" > ${STATIC_ROOT}/data/www/sig${IA}/sighello.html

# The 'python3 -m http.server --bind' command will be run by webapp...
EOL
cat $file

# Create script to test the running SIG
file=${cfgdir}/test_sig${IA}.sh
cat >$file <<EOL
#!/bin/bash
python3 -m http.server --bind 172.16.${IdLocal}.1 ${ServePort}
EOL
cat $file
